language: java
  
addons:
  sonarqube: true
  
sudo: required

env:
  global:
    - secure: "O22oxSd+56CMjG9kXYA7M3LxTdJzglEgsgPMOHrhTvK7H+wIWERf2ZhtG/LJ538EJgNg0ZLEIS0VO80Lukt7OgbK4ZDlViLU+9gQR6L2qAoyAL6c5h3m03+ONRGf7gFPf7d2RGZcXIgZtPAqTZUIjlk8AKvlhYm2my8OSQT2RIBR/TlYxd76XC5h0ehaS5vtjVM4tmwcVE9BVrKKxi0YV1LluyxIbV9dkY0gTYyjGKQKH8iv4tF4LZiNWu556vVk/RMs/OMM9bmB8kX1E+mjHfpCR6Y0hz+no+j6v8wGuCzb7mNfDK0joA63pase0UK0ZV4GlM7SDLEP318wmI3yDfLvOJuAesMAZiCLuNQErtqALA7FavTYxKiHbMS43nJqaXjcqw7hYSyFzGowtC71etmFXkqq5kL5TuUCWYJTVIJm/WtXPcnND8gc3enFsFDLXNBGWFU1tCqlABof7ZDQGh2T63PiJkkcwcGu1Qcdzxru9PxdyMjM/GU+jArHRkbD9xEUrr+wpZk5bq4NcK6wrdbjSZ0fw1n7qwC0ZbI45AZewbPsj3yVgIfjT3z33CARSo8Dq1Wh2WIoOTUd2kFQX1HNXCmxIJLQ2qJkuQo4Uo4gzsvLECQVlYm63LanH9EjRdWEKwCuMt6l/M+lNynSKApljoQG6eVvSqJj8Up7CI8="
    - secure: "ZQEHth95lRVxPVfGqcAnxOS4Tpk2oy5cEtje2gNJso5EnaoEUyrgEffQJSk02Zv0cgJg//qW8Fp9cWTdcM34stlHDnDnSSaH+0VKAZvMWXxHBfaJJogADj2eR1O8JUYWljT5ameV481BxPNxT/Hzu5z5gnC/cZ1Ba7M44C/hqGwf/Obg9Mcy3tebf7UxpRfhvHRq+Y89P7mNK1Id3bYa6nswrnWI7ThGLB8uk+Fjzf+gVMK3wYjv5wFo2nrso04YBoBl8bhbQuYXi1so6JdnXKrqSejtjRUP+V9fCrcqAQXLHUHno+rcj35kjRFwH9m/dxfY9pOcIDhUHXXMVHK0yFNNtKxw1ckrwsw6PqHTErO/hvBtyUMR+2aT7Foy8K9FpMekJ8f+s0OlQ0fmUeZnDND9b6p5rH64ExwkhU7MLTsz/Kt3hlF20gn6c6SwioDj6YU0d1uoEenCoBcEUP1OJYAipF6mp66vRkMpfaHaMSUUKsg5RxD4tqOsuvgXiJGoU02kY2USTYWDrj4Lhcwk9KsrJ0vGb5YtyI31r2H1uctjJ8Y5/0+ZMVttmnVC6OrCIc5L49frUoGjL9A2dlOINY15N4XqUGHgqQp+yGj/w3eF6IE/xCoKCNu7uLcdc+uCqtrpcqRtqvtzJsBzRjaajSCSfWslzxGGRHq8nrbqdtg="
    - secure: "MTez+Rpb8ldITFn+ltQAY6+RUiFpc4BO2er4lgcN2WVaa2CNOv8seyIiYiWbfCt66y5dickIzhs5eqM5hh/lrTgVESW0xSBUoUKVzFHWGSrbwXfwClQXPoihCYbbPHAvrd0j44QXkX721O4DkjkAyWpKIKceBWJkYFdbazXinefx887uWptdRmc1iZa/hqEvy83s8D5r4WuF4x6Gx1ZIrmFZCq6+ULjrUUyCezZ3Tl9qyIAZH0KCecxJOhoh8rVKXNKX0RFRizAqMzWBQCLYshzdFOfh4HWLQ74KoGReK/FOiQMS2E7VvlBJrlVqXAAOpyWt+rqtraK1if/vovIkO6vj6HwB3l3CLoKJebAKzivK9DkKXzcONmnkWMEWErsNOVXAshRCR0nvB87bvYQgy7bNwZkAD/vIVTbM0IYkQtja/dG1vFauhFfHKAdl/zg6iHxGUl3t3qOzYDNJWol4QEOh2uFcIPaDL5L3fqOLzn/EDUgM1NTmgQFh6qaOAtO30DDJFyqyCWS/ykmZeiTJ/Rdu3FAPjrS1wS5xDYJiwytSJxHddwJPBDz3FM3euQ5grFmcVkDGD9Fd5m1fFfHEMjdgXsaolwcbGChrblfuRqW9wqxKjnxFNv8W2rc7i1GI9WVCGGAjREOy4/3HFDKLU8QnuzEqMq6/eU/fGwSvjAY="
before_script:
  - chmod +x sonarscanner.sh

jdk:
  - oraclejdk8

install: true

addons:
  apt:
    packages:
      - oracle-java8-installer
   
  

script: 
  - ./sonarscanner.sh  
