language: java
  
addons:
  sonarqube: true
  
sudo: required


before_script:
  - chmod +x sonarscanner.sh

jdk:
  - oraclejdk8

install: true

addons:
  apt:
    packages:
      - oracle-java8-installer
   
  


script: 
  - ./sonarscanner.sh  
